#!/bin/bash
# Tasuki Engine — Project Facts
# Auto-generates a verified facts file from actual project state.
# This is the SINGLE SOURCE OF TRUTH that agents load first.
# ~200 tokens — cheap, always loaded, prevents hallucination.
#
# Facts are VERIFIED by reading real files, not guessed.
# If a fact can't be verified, it's not included.
#
# Output: .tasuki/config/project-facts.md
# Usage: bash facts.sh [/path/to/project]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Override strict mode for facts generation — greps may legitimately return no matches
set +e
set +o pipefail

generate_facts() {
  local project_dir="${1:-.}"
  project_dir="$(cd "$project_dir" && pwd)"
  local output="$project_dir/.tasuki/config/project-facts.md"

  mkdir -p "$(dirname "$output")"

  local project_name
  project_name=$(basename "$project_dir")
  local date
  date=$(date '+%Y-%m-%d %H:%M')

  {
    echo "# Project Facts — $project_name"
    echo "# Auto-generated by tasuki. VERIFIED from actual files."
    echo "# Last updated: $date"
    echo "# Load this FIRST. If something here contradicts your assumptions, trust THIS."
    echo ""

    # === STACK (verified from files) ===
    echo "## Stack"
    detect_verified_stack "$project_dir"
    echo ""

    # === PATHS (verified to exist) ===
    echo "## Paths (verified)"
    detect_verified_paths "$project_dir"
    echo ""

    # === COMMANDS (verified runnable) ===
    echo "## Commands"
    detect_verified_commands "$project_dir"
    echo ""

    # === VERSIONS (from lockfiles/configs) ===
    echo "## Versions"
    detect_verified_versions "$project_dir"
    echo ""

    # === STRUCTURE (file counts, real) ===
    echo "## Structure"
    detect_structure "$project_dir"
    echo ""

    # === ENV VARS (from .env.example, not .env) ===
    echo "## Environment Variables"
    detect_env_vars "$project_dir"
    echo ""

    # === DO NOT (from error memory) ===
    echo "## Do NOT (learned from errors)"
    load_error_memory "$project_dir"

  } > "$output"

  local lines
  lines=$(wc -l < "$output")
  local tokens=$((lines * 4))  # rough estimate: 4 tokens per line

  log_success "Project facts: $output ($lines lines, ~${tokens} tokens)"
}

detect_verified_stack() {
  local dir="$1"

  # Language — verify by finding actual source files
  if find "$dir" -name "*.py" -not -path "*/node_modules/*" -not -path "*/__pycache__/*" 2>/dev/null | grep -q .; then
    echo "- Language: Python"
    # Framework — verify from imports in actual code
    if grep -rq "from fastapi\|import fastapi" "$dir" --include="*.py" 2>/dev/null; then
      echo "- Framework: FastAPI"
    elif grep -rq "from django\|import django" "$dir" --include="*.py" 2>/dev/null; then
      echo "- Framework: Django"
    elif grep -rq "from flask\|import flask" "$dir" --include="*.py" 2>/dev/null; then
      echo "- Framework: Flask"
    fi
  fi

  if find "$dir" -name "*.ts" -o -name "*.tsx" 2>/dev/null | grep -v node_modules | head -1 | grep -q .; then
    echo "- Language: TypeScript"
  elif find "$dir" -name "*.js" -o -name "*.jsx" 2>/dev/null | grep -v node_modules | head -1 | grep -q .; then
    echo "- Language: JavaScript"
  fi

  if [ -f "$dir/go.mod" ]; then echo "- Language: Go"; fi
  if [ -f "$dir/Gemfile" ]; then echo "- Language: Ruby"; fi
  if [ -f "$dir/composer.json" ]; then echo "- Language: PHP"; fi
  if [ -f "$dir/pom.xml" ] || [ -f "$dir/build.gradle" ]; then echo "- Language: Java"; fi

  # Database — verify from config/docker
  if grep -rq "postgres\|postgresql\|5432" "$dir/docker-compose"*.yml "$dir/compose"*.yml "$dir/.env"* 2>/dev/null; then
    echo "- Database: PostgreSQL"
  fi
  if grep -rq "mysql\|3306" "$dir/docker-compose"*.yml 2>/dev/null; then
    echo "- Database: MySQL"
  fi
  if grep -rq "mongodb\|mongo\|27017" "$dir/docker-compose"*.yml 2>/dev/null; then
    echo "- Database: MongoDB"
  fi

  # ORM — verify from imports
  if grep -rq "from sqlalchemy\|import sqlalchemy" "$dir" --include="*.py" 2>/dev/null; then
    echo "- ORM: SQLAlchemy"
  fi
  if grep -rql "prisma" "$dir/package.json" 2>/dev/null; then
    echo "- ORM: Prisma"
  fi

  # Frontend framework — verify from config files
  if [ -f "$dir/next.config.js" ] || [ -f "$dir/next.config.mjs" ] || [ -f "$dir/next.config.ts" ]; then
    echo "- Frontend: Next.js"
  elif [ -f "$dir/svelte.config.js" ]; then
    echo "- Frontend: SvelteKit"
  elif [ -f "$dir/nuxt.config.ts" ] || [ -f "$dir/nuxt.config.js" ]; then
    echo "- Frontend: Nuxt"
  fi
}

detect_verified_paths() {
  local dir="$1"

  # Only list paths that ACTUALLY EXIST
  for path in app src backend api server frontend client web; do
    [ -d "$dir/$path" ] && echo "- $path/ (exists)"
  done

  for path in tests test spec __tests__; do
    [ -d "$dir/$path" ] && echo "- $path/ (tests)"
  done

  for path in alembic migrations db/migrate prisma/migrations; do
    [ -d "$dir/$path" ] && echo "- $path/ (migrations)"
  done

  # Docker
  [ -f "$dir/Dockerfile" ] && echo "- Dockerfile (exists)"
  [ -f "$dir/docker-compose.yml" ] && echo "- docker-compose.yml (exists)"
  [ -f "$dir/compose.yml" ] && echo "- compose.yml (exists)"

  # CI
  [ -d "$dir/.github/workflows" ] && echo "- .github/workflows/ (CI/CD)"
}

detect_verified_commands() {
  local dir="$1"

  # Package manager — verify from lockfiles
  if [ -f "$dir/pnpm-lock.yaml" ]; then echo "- Package manager: pnpm"
  elif [ -f "$dir/yarn.lock" ]; then echo "- Package manager: yarn"
  elif [ -f "$dir/bun.lockb" ]; then echo "- Package manager: bun"
  elif [ -f "$dir/package-lock.json" ]; then echo "- Package manager: npm"
  elif [ -f "$dir/requirements.txt" ]; then echo "- Package manager: pip"
  elif [ -f "$dir/Pipfile" ]; then echo "- Package manager: pipenv"
  elif [ -f "$dir/pyproject.toml" ]; then echo "- Package manager: poetry/pip"
  fi

  # Run commands — verify from package.json scripts or known files
  if [ -f "$dir/package.json" ]; then
    local scripts
    scripts=$(python3 -c "import json; d=json.load(open('$dir/package.json')); [print(f'- npm run {k}') for k in d.get('scripts',{}).keys()]" 2>/dev/null || true)
    [ -n "$scripts" ] && echo "$scripts"
  fi

  if [ -f "$dir/Makefile" ]; then
    echo "- Makefile targets: $(grep -E '^[a-z].*:' "$dir/Makefile" 2>/dev/null | sed 's/:.*//' | head -5 | tr '\n' ', ' | sed 's/,$//')"
  fi

  # Migration command
  [ -d "$dir/alembic" ] && echo "- Migrations: alembic upgrade head"
  [ -f "$dir/manage.py" ] && echo "- Migrations: python3 manage.py migrate"
}

detect_verified_versions() {
  local dir="$1"

  # Python version
  if [ -f "$dir/.python-version" ]; then
    echo "- Python: $(cat "$dir/.python-version")"
  elif [ -f "$dir/pyproject.toml" ]; then
    local pyver
    pyver=$(grep -oE 'python_requires.*"[><=!]*[0-9.]+"' "$dir/pyproject.toml" 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+' || true)
    [ -n "$pyver" ] && echo "- Python: >= $pyver"
  fi

  # Node version
  if [ -f "$dir/.nvmrc" ]; then
    echo "- Node: $(cat "$dir/.nvmrc")"
  elif [ -f "$dir/.node-version" ]; then
    echo "- Node: $(cat "$dir/.node-version")"
  elif [ -f "$dir/package.json" ]; then
    local nodever
    nodever=$(python3 -c "import json; d=json.load(open('$dir/package.json')); print(d.get('engines',{}).get('node',''))" 2>/dev/null || true)
    [ -n "$nodever" ] && echo "- Node: $nodever"
  fi

  # Key dependency versions from requirements.txt or package.json
  if [ -f "$dir/requirements.txt" ]; then
    grep -E '^(fastapi|django|flask|sqlalchemy|alembic|celery|redis|httpx)==' "$dir/requirements.txt" 2>/dev/null | head -5 | while read -r dep; do
      echo "- $dep"
    done
  fi
}

detect_structure() {
  local dir="$1"

  for ext in py ts tsx js jsx go rb java php svelte vue; do
    local count
    count=$(find "$dir" -name "*.$ext" -not -path "*/node_modules/*" -not -path "*/__pycache__/*" -not -path "*/.git/*" 2>/dev/null | wc -l | tr -dc '0-9')
    [ "${count:-0}" -gt 0 ] && echo "- .$ext files: $count"
  done

  local test_count
  test_count=$(find "$dir" \( -name "test_*" -o -name "*.test.*" -o -name "*.spec.*" \) -not -path "*/node_modules/*" 2>/dev/null | wc -l | tr -dc '0-9')
  echo "- Test files: ${test_count:-0}"
}

detect_env_vars() {
  local dir="$1"

  if [ -f "$dir/.env.example" ]; then
    echo "Required (from .env.example):"
    grep -vE '^\s*#|^\s*$' "$dir/.env.example" 2>/dev/null | sed 's/=.*//' | while read -r var; do
      [ -z "$var" ] && continue
      echo "- $var"
    done
  else
    echo "- No .env.example found"
  fi
}

load_error_memory() {
  local dir="$1"
  local errors_dir="$dir/memory-vault/errors"

  if [ -d "$errors_dir" ] && [ "$(find "$errors_dir" -name "*.md" 2>/dev/null | wc -l)" -gt 0 ]; then
    for f in "$errors_dir"/*.md; do
      [ -f "$f" ] || continue
      local rule
      rule=$(grep -A1 "## Rule" "$f" 2>/dev/null | tail -1 || true)
      [ -n "$rule" ] && echo "- $rule"
    done
  else
    echo "- (none yet — errors will be recorded here automatically)"
  fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  generate_facts "$@"
fi
